### ISSUE TITLE
pip install beeware on Ubuntu 18.04

### ISSUE THREAD

**Issue by krishnaTORQUE** [beeware/beeware#10] opened 2019-03-17 21:31 UTC
pip install beeware on **Ubuntu** 18.04
**Python** : **3.6.7**
**pip** : **9.0.1**

**_ERROR_**
- Failed building wheel for pygobject
- Failed building wheel for pycairo
- making **pip** package corrupted

**Comment by freakboy3742** [comment] 2019-12-21 01:47
Marking as a duplicate of #5.

**Closed by freakboy3742** 2019-12-21 01:47 UTC
