### ISSUE TITLE
Compilation andorid error on ubuntu

### ISSUE THREAD

**Issue by main1015** [beeware/beeware#120] opened 2021-08-26 00:16 UTC
**Describe the bug**
I compile the Android app misreporting on ubuntu18 via the ‘ briefcase build android‘ command

**To Reproduce**
1. I created the Android app via 'briefcase create android' 
2. then compiles the Android app via the ‘briefcase build android‘ command
3. has reported an error at this time

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3272281/130880483-a9b74b18-0623-44a3-b8c7-3b07fa19c55f.png)

**Environment:**
- Operating System: ubuntu18
- Python version:3.6
- Software versions:0.3.5

**Comment by kitlycol** [comment] 2021-09-03 09:21
same problems with build android Tutorial app

**Comment by freakboy3742** [comment] 2021-09-05 00:48
I'm not completely sure what is going on here, but it appears to be related to the way cmake is being invoked. Is it possible that you have a version of CMake other than the one provided by the Android SDK?

**Comment by main1015** [comment] 2021-09-05 06:02
@freakboy3742 
The version of the cmake that I use is listed below
![image](https://user-images.githubusercontent.com/3272281/132117192-b686bc5e-b44b-4be6-bc57-69d741e1a04e.png)

**Comment by freakboy3742** [comment] 2021-09-05 22:32
Ok; so you've got a version of Cmake other than the one that has been provided by Android. The Android developer tools also provide cmake (3.6.0-rc2), and that's the version it's expecting to find. 

If you uninstall (or otherwise disable) your "system" version of cmake, does that allow the build to succeed?

**Comment by freakboy3742** [comment] 2021-09-06 22:34
Via beeware/briefcase#615 (which is a second report of the same problem), we've been able to confirm the issue is cmake. This means the issue is with Briefcase, not the tutorial; I'm going to close this issue in favour of that one.

**Closed by freakboy3742** 2021-09-06 22:34 UTC
Labels: bug
