### ISSUE TITLE
Dash Incompatibility

### ISSUE THREAD

**Issue by ethanchansd** [beeware/beeware#96] opened 2021-01-21 10:54 UTC
**Describe the bug**
when importing Dash the app fails to run. No issues in dev environment though

**To Reproduce**
import dash and create/build/run briefcase
app fails to run

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8.7
 - Software versions:
   - Briefcase: 0.3.4

**Comment by freakboy3742** [comment] 2021-01-22 03:22
Thanks for the report. I *think* the issue is related to the binary dependency on Brotli; I'll need to investigate further.

**Comment by freakboy3742** [comment] 2022-03-28 04:19
Closing as I believe this has now been addressed.

**Closed by freakboy3742** 2022-03-28 04:19 UTC
Labels: bug
