### ISSUE TITLE
Hello World app in tutorial fails to open

### ISSUE THREAD

**Issue by apmech707** [beeware/beeware#62] opened 2020-06-29 20:31 UTC
Hi, I am trying to figure out why I get stopped part way through the tutorial and my hello world app doesn't load. The window comes up but it says not responding and I have to force it closed. I have downloaded the dependencies and followed the tutorial to the letter. Any suggestions?

**Comment by mafuber** [comment] 2020-07-01 14:37
I have the same problem

**Comment by freakboy3742** [comment] 2020-07-02 00:25
The BeeWare tutorial includes instructions for macOS, Linux, Windows and iOS; and there are multiple versions of Python that are supported too. Unless you tell us about your *specific* circumstances, it's almost impossible to identify the source of problems. Even the statement "partway through" isn't helpful - how far is "partway"?

The only thing I can advise at present is that if you're running Windows and Python 3.8, what you're described is known behaviour. The tutorial explicitly advises against using Python 3.8 on Windows, but this still seems to catch a lot of people.

If this *doesn't* describe your situation, then provide more details and we can see if we can help.

**Comment by freakboy3742** [comment] 2020-07-11 14:34
Closing as an almost certain duplicate of #64.

**Closed by freakboy3742** 2020-07-11 14:34 UTC
Labels: question
