### ISSUE TITLE
Problem installing app on Android device.

### ISSUE THREAD

**Issue by ujur007** [beeware/beeware#180] opened 2023-01-15 11:32 UTC
### Describe the bug

I have created an application which runs fine on the Linux platform and I wanted to install the same app on Android device but I got error deploying the app to the device. There is error related to module import of the module PIL. But I do not have the PIL module in my  list of imports.

So the application gets installed on the device but when opening the application I get error related to PIL module import.

My list of imports looks like the following.

```
import toga
from toga.style import Pack
from toga.constants import RED
from toga.style.pack import COLUMN, ROW
import bleak
from bleak import BleakScanner
from bleak import BleakClient
from bleak.backends.device import BLEDevice
from functools import partial
import time
import asyncio
```
The error is the following.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bleapp/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'PIL'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'PIL'
	at <python>.java.chaquopy.import_override(import.pxi:20)
	at <python>.java.chaquopy.import_override(import.pxi:60)
	at <python>.[bleapp.app](http://bleapp.app/).<module>(app.py:10)
	at <python>.java.chaquopy.import_override(import.pxi:60)
	at <python>.__main__.<module>(__main__.py:1)
	at <python>.runpy._run_code(runpy.py:87)
	at <python>.runpy._run_module_code(runpy.py:97)
	at <python>.runpy.run_module(runpy.py:207)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.beeware.android.MainActivity.onCreate(MainActivity.java:64)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more

```

### Expected behavior

Application should run the similar to how it runs on Linux.!

### Environment

- Operating System: Linux mint
- Python version: 3.8.10
- Software versions:
  - Briefcase: 0.3.10
  - Toga:
  - ...

### Logs

```
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bleapp/org.beeware.android.MainActivity}: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'PIL'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3761)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3935)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8292)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: com.chaquo.python.PyException: ModuleNotFoundError: No module named 'PIL'
	at <python>.java.chaquopy.import_override(import.pxi:20)
	at <python>.java.chaquopy.import_override(import.pxi:60)
	at <python>.[bleapp.app](http://bleapp.app/).<module>(app.py:10)
	at <python>.java.chaquopy.import_override(import.pxi:60)
	at <python>.__main__.<module>(__main__.py:1)
	at <python>.runpy._run_code(runpy.py:87)
	at <python>.runpy._run_module_code(runpy.py:97)
	at <python>.runpy.run_module(runpy.py:207)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.beeware.android.MainActivity.onCreate(MainActivity.java:64)
	at android.app.Activity.performCreate(Activity.java:8241)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3734)
	... 12 more
```

**Comment by freakboy3742** [comment] 2023-01-15 23:02
It's impossible for us to diagnose a problem if you don't provide details. You've given us a bare minimum selection from the final stack trace, and no details about the app itself, other than a selection of imports - despite the bug reporting form having an *explicit* section asking for reproduction instructions.

So we'll have to guess at the cause. In this case, while your code doesn't explicitly use PIL, your dependencies may be using PIL. However, as you haven't provided a full stack trace, it's impossible for us to tell which one. 

Closing on the basis that there is insufficient information to reproduce the problem.

**Closed by freakboy3742** 2023-01-15 23:02 UTC
Labels: bug

**Comment by mhsmith** [comment] 2023-01-16 19:23
This is a full stack trace: the "12 more" just indicates that they're the same frames as were already shown for the previous exception in the chain.

What we need to know is what is on bleapp/app.py line 10. The 10th line of the imports you posted is `import time`, so I assume that isn't it.

**Comment by freakboy3742** [comment] 2023-01-16 23:48
Stack trace was lazy wording on my part - I was referring to the rest of the Briefcase logs.

**Comment by ujur007** [comment] 2023-01-17 04:57
Hi, Sorry for the inconvenience.
Actually, I then looked at Beeware documentation and reminded myself of adding extra modules inside the requirements sections of packages in .toml file. 
That has solved the issue.
