### ISSUE TITLE
Running macos target fails

### ISSUE THREAD

**Issue by hendrikmaus** [beeware/beeware#2] opened 2018-05-04 07:52 UTC
Using Python 3.6.5, I created a new app with a run of `beeware new`; using all the default values that cookiecutter suggests as a default path.

Running `beeware build macos` works out fine, but running it fails:

Error: `LSOpenURLsWithRole() failed with error -10810 for the file (...)`

Full output:

```
$ beeware run macos
Running Briefcase...
>>> python setup.py macos -s

running macos

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-cocoa==0.3.0.dev8
  Using cached https://files.pythonhosted.org/packages/21/34/89be59bdf2877c8b074dd7d6be26e77a6ffa488be1d47bc9b932579062d0/toga_cocoa-0.3.0.dev8-py3-none-any.whl
Collecting rubicon-objc>=0.2.10 (from toga-cocoa==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/35/b0/aa6d839057126991d16a591c74e24c075797db7436d6c0d6e655a3e15b3a/rubicon_objc-0.2.10-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev8 (from toga-cocoa==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/a4/2e/4757cadb2206e2f6bb6136fda395dbec2d84bda86b77b5713f435b0fdb60/toga_core-0.3.0.dev8-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev8->toga-cocoa==0.3.0.dev8)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-cocoa
Successfully installed rubicon-objc-0.2.10 toga-cocoa-0.3.0.dev8 toga-core-0.3.0.dev8 travertino-0.1.2
 * Installing project code...
Processing /Users/hendrikmaus/Development/playground/beeware/appname
Building wheels for collected packages: appname
  Running setup.py bdist_wheel for appname ... done
  Stored in directory: /private/var/folders/hc/bd6lpj810hl1t9h3ymt32f7c0000gn/T/pip-ephem-wheel-cache-stfbp900/wheels/04/b4/66/794e976fb020ab3df2fa991025c119ec2795bd43b2f85e95cc
Successfully built appname
Installing collected packages: appname
Successfully installed appname-0.0.1
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
Starting App Name.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/hendrikmaus/Development/playground/beeware/appname/macOS/App Name.app.

App started.
```

**Comment by freakboy3742** [comment] 2018-05-04 15:42
Thanks for the report. My guess is that this will be due to pybee/briefcase#108. Could I get you to check the README file in  `~/.cookicutters/Python-macOS-template`, and tell me what Python version it describes? If my suspicion is correct, it will say Python 2.7

**Comment by hendrikmaus** [comment] 2018-05-07 11:12
Sure thing, I got this file, which seems to be targeting Python 3.6


```
Python macOS Template
=====================

A template for building Python apps that will run under macOS.

**This repository branch contains a template for Python 3.6**.
Other Python versions are available by cloning other branches of repository.

Using this template
-------------------

The easiest way to use this project is to not use it at all - at least,
not directly. `Briefcase <https://github.com/pybee/briefcase/>`__ is a
tool that uses this template, rolling it out using data extracted from
your ``setup.py``.

However, if you *do* want use this template directly...

1. Install `cookiecutter`_. This is a tool used to bootstrap complex project
   templates::

    $ pip install cookiecutter

2. Run ``cookiecutter`` on the Python-macOS template::

    $ cookiecutter https://github.com/pybee/Python-macOS-template --checkout 3.6

3. `Download the Python Apple support package for macOS`_, and extract it. This
   will give you four frameworks.

   * ``BZip2.framework``

   * ``OpenSSL.framework``

   * ``XZ.framework ``

   * ``Python.framework``

   Alternatively, you can download the `Python-Apple-support`_ project, and
   build your own versions of these frameworks.

   These framework directories should be placed in the same directory as
   the ``app`` and ``app_packages`` directories generated by the cookiecutter
   project template - the ``Contents`` subdirectory of the main application
   bundle.

4. Add your code to the template. At the very minimum, you need to have an
   ``app/<app name>/__main__.py`` file that defines an entry point that
   will start your application. If ``<app name>`` contains a dash, it will be
   converted to an underscore in the expected package name

   If your code has any dependencies, they should be installed under the
   ``app_packages`` directory.


If you've done this correctly, a project with a formal name of ``My Project``,
with an app name of ```my-project`` should have a directory structure that
looks something like::

    My Project.app/
        Contents/
            MacOS/
                My Project
            Resources/
                app/
                    my_project/
                        __init__.py
                        __main__.py
                app_packages/
                    ...

The top level directory should identify as an macOS application, and can be
distributed as a standalone package.

Next steps
----------

Of course, just running Python code isn't very interesting by itself - you'll
be able to output to the console, and see that output in XCode, but if you
tap the app icon on your phone, you won't see anything - because there isn't a
visible console on an iPhone.

To do something interesting, you'll need to work with the native macOS system
libraries to draw widgets and respond to screen taps. The `Rubicon`_
Objective C bridging library can be used to enable an easy interface with the
macOS system libraries. You could also use the `toga`_ library to provides a
cross-platform widget toolkit that supports macOS.

If you have any external library dependencies (like ``toga``, or anything other
third-party library), you should install the library code into the
``app_packages`` directory. This directory is the same as a  ``site_packages``
directory on a normal Python install.

.. _cookiecutter: http://github.com/audreyr/cookiecutter
.. _Download the Python Apple support package for macOS: https://s3-us-west-2.amazonaws.com/pybee-briefcase-support/Python-Apple-support/3.6/macOS/Python-3.6-macOS-support.b1.tar.gz
.. _Python-Apple-support: http://github.com/pybee/Python-Apple-support
.. _toga: http://pybee.org/toga
.. _Rubicon: http://github.com/pybee/rubicon-objc
```

**Comment by freakboy3742** [comment] 2018-05-07 14:54
Interesting... that wasn't what I was expecting. 

The next thing to check - run the app file manually, and see what error is reported. Based on the stack trace you showed earlier, you have a project in a directory `/Users/hendrikmaus/Development/playground/beeware/appname`. From the shell, change into that directory, then run:
```
macOS/App\ Name.app/Contents/MacOS/App\ Name
```
That's what is being executed when you double click on the icon (or use `beeware run`). What error do you get?

**Comment by jrwdunham** [comment] 2018-08-03 17:28
@freakboy3742 I am having a similar issue.

When I run `beeware run macOS` on the toga/examples/beeliza app (Mac OS 10.13.5, Python 3.5.3), I see this among output similar to the above:

    toga 0.3.0.dev9 has requirement toga-cocoa==0.3.0.dev9; sys_platform == "darwin", but you'll have toga-cocoa 0.2.15 which is incompatible.

Then when I run the equivalent of the command you asked @hendrikmaus to run, I get the following:

    $ macOS/Beeliza.app/Contents/MacOS/Beeliza

    Traceback (most recent call last):
      File "/Users/someuser/Development/toga/toga/examples/beeliza/macOS/Beeliza.app/Contents/Resources/python/lib/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Users/someuser/Development/toga/toga/examples/beeliza/macOS/Beeliza.app/Contents/Resources/python/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/someuser/Development/toga/toga/examples/beeliza/macOS/Beeliza.app/Contents/Resources/app/beeliza/__main__.py", line 1, in <module>
        from beeliza.app import main
      File "/Users/someuser/Development/toga/toga/examples/beeliza/macOS/Beeliza.app/Contents/Resources/app/beeliza/app.py", line 5, in <module>
        from toga.constants import ROW, COLUMN
    ImportError: cannot import name 'ROW'

So it looks like outdated versions of toga-core and toga-cocoa are getting installed by default.

To get it to work, I had to specify the 0.3.0 toga-cocoa requirement in the platform requirements:

    $ git diff
    diff --git a/examples/beeliza/setup.py b/examples/beeliza/setup.py
    index 91c8765..ee8cbdf 100644
    --- a/examples/beeliza/setup.py
    +++ b/examples/beeliza/setup.py
    @@ -52,7 +52,7 @@ setup(
             # Desktop/laptop deployments
             'macos': {
                 'app_requires': [
    -                'toga-cocoa',
    +                'toga-cocoa==0.3.0.dev9',
                 ]
             },
             'linux': {

**Comment by freakboy3742** [comment] 2018-08-04 01:32
@jrwdunham That's very helpful - thanks. 

It appears the bug appears to be with Beeliza, not Briefcase. Briefcase is doing exactly what it's been told to do; the problem is that Beeliza isn't pinning the right Toga version in it's requirements.

**Comment by BrendanSimon-SEPL** [comment] 2019-07-31 11:35
Is there a planned fix for this?

**Comment by freakboy3742** [comment] 2019-12-21 01:45
We've restructured the `beeware` package so that it's a pure metapackage, deferring all code generation to [briefcase](https:/github.com/beeware/briefcase). 

The Beeliza example has also been updated (although it needs to be updated to use briefcase 0.3 pyproject.toml configurations)

**Closed by freakboy3742** 2019-12-21 01:45 UTC
