### ISSUE TITLE
Error with running helloworld

### ISSUE THREAD

**Issue by nagayev** [beeware/beeware#107] opened 2021-05-30 16:05 UTC
**Describe the bug**
Hello world app crashed.

**To Reproduce**
1. Create hello-world app using official guide.
2. Run `briefcase run`
3. See error
`ImportError: cannot import name GLib, introspection typelib not found`

**Expected behavior**
Working app

**Screenshots**
![Screenshot from 2021-05-30 19-03-46](https://user-images.githubusercontent.com/16555544/120111244-dbeedc80-c179-11eb-842e-6d99e9754808.png)

**Environment:**
 - Operating System: Fedora 34
 - Python version: 3.9.5
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: default

**Comment by freakboy3742** [comment] 2022-03-28 04:20
Closing as a duplicate of #70. Packaging on Linux is Hard :-(

**Closed by freakboy3742** 2022-03-28 04:20 UTC
Labels: bug
