### ISSUE TITLE
briefcase run fails

### ISSUE THREAD

**Issue by compromyse** [beeware/beeware#141] opened 2022-02-08 05:36 UTC
Whenever I run `briefcase run -u`, the application launches but as soon as i enter a name, this error occours:
```(beeware-venv) -----------------------------------------------------------------------------------------------------------------------------------
~/laboratory/beeware-tutorial/beewaretutorial » briefcase run                                                                                                                compromyse@spoofy

[beewaretutorial] Starting app...

[GTK+] Not implemented: TextInput.set_alignment()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.set_font()
[GTK+] Not implemented: TextInput.clear_error()
[GTK+] Not implemented: TextInput.set_on_lose_focus()
[GTK+] Not implemented: TextInput.set_on_gain_focus()
[GTK+] Not implemented: Button.set_background_color()
/tmp/.mount_beewar3sNa7K/usr/app_packages/toga_gtk/app.py:40: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.native.set_wmclass(app.interface.name, app.interface.name)

(__main__.py:73611): Gtk-WARNING **: 10:58:40.072: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Papirus-Dark/48x48/status/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Papirus-Dark/48x48/status/image-missing.svg: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_font_options_get_variations (gdk-pixbuf-error-quark, 5)
/tmp/.mount_beewar3sNa7K/AppRun: line 7: 73611 Aborted                 (core dumped) $APPDIR/usr/bin/python3 -s -m beewaretutorial "$@"

Unable to start app beewaretutorial.
(beeware-venv) -----------------------------------------------------------------------------------------------------------------------------------
~/laboratory/beeware-tutorial/beewaretutorial »                                                                                                                        200 ↵ compromyse@spoofy
```
I expected to see a pop up with "Hello, name"

![image](https://user-images.githubusercontent.com/71056504/152924532-bb33e8d2-8f5e-4293-91db-baccb11337b6.png)

 - Operating System: Ubuntu 20.04
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev30

It works fine with `briefcase dev`

**Comment by freakboy3742** [comment] 2022-03-28 04:28
Closing as a duplicate of the cluster of Linux packaging issues, currently being tracked by #70.

**Closed by freakboy3742** 2022-03-28 04:28 UTC
Labels: bug
