### ISSUE TITLE
Linux build not working

### ISSUE THREAD

**Issue by praveen-manohar** [beeware/beeware#70] opened 2020-08-01 11:54 UTC
Hi, When I try to build beeware(toga+briefcase) app in Linux its shows the following error. Kindly let me know the reason for this error.

Error:
-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file /home/zerrow/Desktop/beeware/helloworld/linux/Hello World/Hello World.AppDir/usr/bin/python3.8 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libpthread.so.0 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libdl.so.2 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libutil.so.1 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libm.so.6 
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libc.so.6 
Deploying dependencies for ELF file /home/zerrow/Desktop/beeware/helloworld/linux/Hello World/Hello World.AppDir/usr/lib/python3.8/lib-dynload/_lsprof.cpython-38-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/zerrow/Desktop/beeware/helloworld/linux/Hello World/Hello World.AppDir/usr/lib/python3.8/lib-dynload/_codecs_iso2022.cpython-38-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/zerrow/Desktop/beeware/helloworld/linux/Hello World/Hello World.AppDir/usr/lib/python3.8/lib-dynload/_codecs_jp.cpython-38-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/zerrow/Desktop/beeware/helloworld/linux/Hello World/Hello World.AppDir/usr/lib/python3.8/lib-dynload/_gdbm.cpython-38-x86_64-linux-gnu.so 
ERROR: Could not find dependency: libgdbm.so.3 
ERROR: Failed to deploy dependencies for existing files 

Error while building app helloworld.

Device:
 - Operating System: linux mint 20
 - Python version: 3.8

**Comment by freakboy3742** [comment] 2020-08-02 05:30
Thanks for the report - however, we need a lot more detail to be able to reproduce this problem. I also note that in order to log this bug, you would have had to *delete* a whole lot of templated detail that would prompted you to provide all the missing details. We ask for explicit details for a reason: "It didn't work" or "it didn't work, here's a stack trace" doesn't really help us diagnose your problem.

In order to provide any details here, we need to know:
* Exactly what you were trying to build (it looks like it might be the BeeWare tutorial "hello world", but that would be a guess)
* What version of Briefcase you are using
* What version of the Python support package you are using.

I strongly suspect that what you've found is a variant on beeware/briefcase#420. This has been fixed in the development version of Briefcase, which should be released in a stable version in the near future. However, without more details, it's impossible to say for sure.

**Comment by praveen-manohar** [comment] 2020-08-04 06:31
* it's just HelloWorld code just display the tutorial screen with a toga

* Briefcase - 0.3.3
* Python - 3.8.2

**Comment by freakboy3742** [comment] 2020-09-06 01:02
It looks like we're having some persistent Linux packaging issues - beeware/briefcase#470 is the ticket tracking the problem. It appears that we're not driving the AppImage tool correctly, resulting in binaries that aren't correctly isolated from the environment.

**Comment by freakboy3742** [comment] 2022-03-28 04:29
An update: Linux packaging appears to be a consistent problem; beeware/briefcase#458, beeware/briefcase#470, beeware/briefcase#481, beeware/briefcase#504, beeware/briefcase#583, beeware/briefcase#625, beeware/briefcase#631 (and probably more) describe variations on a theme of missing/incompatible Linux binary versions in the compiled AppImage.

**Comment by mavavilj** [comment] 2022-04-11 10:24
I have this same problem on OpenSuse Tumbleweed 20220303.

Error appears at this point:

https://docs.beeware.org/en/latest/tutorial/tutorial-3.html#running-your-app

Error is:

```
~/Documents/codings/beeware/helloworld> briefcase build --no-docker
Downloading linuxdeploy-x86_64.AppImage...
################################################## 100%
Patched ELF header of linuxdeploy AppImage.

[helloworld] Building AppImage...

linuxdeploy version 1-alpha (git commit ID ed42a40), GitHub actions build 76 built on 2022-04-01 01:21:23 UTC

-- Creating basic AppDir structure -- 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/bin/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/applications/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/16x16/apps/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/32x32/apps/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/64x64/apps/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/128x128/apps/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/256x256/apps/ 
Creating directory /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/share/icons/hicolor/scalable/apps/ 

-- Deploying dependencies for existing files in AppDir -- 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/bin/python3.10 
Skipping deployment of blacklisted library /lib64/libpthread.so.0 
Skipping deployment of blacklisted library /lib64/libdl.so.2 
Skipping deployment of blacklisted library /lib64/libutil.so.1 
Skipping deployment of blacklisted library /lib64/libm.so.6 
Skipping deployment of blacklisted library /lib64/libc.so.6 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/python3.10/lib-dynload/_posixsubprocess.cpython-310-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/python3.10/lib-dynload/termios.cpython-310-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/python3.10/lib-dynload/math.cpython-310-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/python3.10/lib-dynload/_heapq.cpython-310-x86_64-linux-gnu.so 
Deploying dependencies for ELF file /home/mavavilj/Documents/codings/beeware/helloworld/linux/appimage/Hello World/Hello World.AppDir/usr/lib/python3.10/lib-dynload/_gdbm.cpython-310-x86_64-linux-gnu.so 
ERROR: Could not find dependency: libgdbm.so.5 
ERROR: Failed to deploy dependencies for existing files 

Error while building app helloworld.
```

**Comment by mavavilj** [comment] 2022-04-11 10:38
On OpenSuse Tumbleweed 20220303 the previous problem is fixed by creating the symlink:

`sudo ln -s /usr/lib64/libgdbm.so.6 /usr/lib64/libgdbm.so.5`

Then a similar issue pops up with libffi, which is fixed with:

`sudo ln -s /usr/lib64/libffi.so.8 /usr/lib64/libffi.so.6`

**Comment by freakboy3742** [comment] 2022-04-12 00:00
@mavavilj The build might succeed, but I wouldn't rely on it *working* across the board; the .N suffix indicates binary versioning. 

In your specific case, the error is being caused because you're building in an environment that is incompatible with the support package it's linking against. We use docker because the support package is explicitly build using Ubuntu 18.04 as a base image. If you're using a recent OpenSuse, a number of core libraries (like GDBM and FFI) will be incompatible. You need to either:
* use Docker; or
* use Ubuntu 18.04; or
* Build your own version of the Linux support package (which will limit users of your AppImage to users with a GLibC version >= the one you have).

**Comment by mavavilj** [comment] 2022-04-12 09:50
> - Build your own version of the Linux support package (which will limit users of your AppImage to users with a GLibC version >= the one you have).

How is this done?

Also, not wanting to sound picky, but this sounds like the library is not perhaps very "soundly" constructed, if it cannot operate with rolling release distros?

**Comment by mavavilj** [comment] 2022-04-12 13:56
Specifically, I don't think requiring Docker on Linux-only development is a good practice.

**Comment by freakboy3742** [comment] 2022-04-12 22:50
@mavavilj Perhaps you should invest a little time working out how something works before you declare that it is not "soundly constructed" or "unideal".

This is a problem entirely of Linux's making. As a result, the solution is baroque. If I compile a binary on Windows 11, it will run on Windows NT, as long as I don't use any Windows 11 (or 10, or 7,...) APIs; and there are easily accessible compiler flags to ensure this doesn't happen. Likewise for macOS, iOS and Android. Not so on Linux. Linux binaries are barely portable between two machines with the *same* operating system.

An AppImage is a way of packaging a complete set of libraries needed to start an app into a standalone bundle. However, you need a set of libraries to bootstrap the AppImage executable - that's GLibC. The version of GLibC that is used pins the "oldest" machine that can run the run the resulting AppImage binary. We've chosen Ubuntu 18.04 as a baseline because it's old enough to cover most installs you're likely to see in practice (remember that Ubuntu 14.04 is still supported as an LTS release. There are still instances of many instances of RHEL5 running in the world).

The process of building the AppImage then involves walking the dependency tree in the libraries that are part of the binary, pulling in any other library that is referenced. In order to do this, you need a self-consistent set of binaries. To save the end-user the effort of having to compile everything from scratch (and to save ourselves the headache of trying to diagnose compilations problems on alien machines), we provide a version of Python compiled on Ubuntu 18.04.

This means that the AppImage binary needs to be compiled *on* an Ubuntu 18.04 machine. Docker is the easiest way to reproduce this reliably - and has the added benefit that it's a clean and reproducible environment, without any "extra" packages from the user interfering with the build. Docker is a sufficiently ubiquitous piece of tooling in the software development ecosystem at this point - especially on Linux - that I don't consider it even remotely controversial to require it. Note, however, that Docker is only required for the *developer* who is packaging the app. The AppImage that is produced doesn't use Docker at all.

Even then - if you want to build *without* Docker, you can. However, you then need to take responsibility for providing *all* the pieces - including a Python support library that is consistent with the rest of your development environment. 

The default Briefcase Python Linux support build can run on any Ubuntu after 18.04, as well as any Fedora, Mint, Arch, SuSE, or another other distro of a similar vintage - which is to say most desktop Linux users. If you're using a Tumbleweed SuSE distro, that means only people with the very latest operating systems installed will be able to use your binary. Maybe that doesn't matter to you; but as a general solution, it's not viable. 

Could you use VirtualBox instead of Docker? Sure. An Ubuntu 18.04 VirtualBox will give you the same environment as an Ubuntu 18.04 Docker image, so within that VirtualBox you could use `--no-docker` and get an internally consistent build. If you want to go down that path, go right ahead. We've chosen to use Docker as the default way of getting the same result.

**Comment by mavavilj** [comment] 2022-04-12 23:27
But this is what I don't still understand:

> @mavavilj The build might succeed, but I wouldn't rely on it _working_ across the board

**Comment by freakboy3742** [comment] 2022-04-12 23:31
@mavavilj I've just written a long explanation of why Ubuntu 18.04 is is needed. And *Some* developers prefer using rolling distros. Others do not. This is why LTS versions exist.

As for why the build might succeed: `/usr/lib64/libgdbm.so.6` and `/usr/lib64/libgdbm.so.5` are different versions of GDBM. Linking one for the other will satisfy the baseline "does the file exist" requirement, but at runtime, when symbols are loaded dynamically, you may (almost certainly will) discover missing symbols, or symbols that behave differently.

Toga does *not * require Python 3.7. Toga works with any Python version *from* Toga 3.7. It's up to you which version you use.

**Comment by freakboy3742** [comment] 2022-04-12 23:34
Which part of "Python 3.7 or higher" is ambiguous?

**Comment by mavavilj** [comment] 2022-04-12 23:43
> As for why the build might succeed: `/usr/lib64/libgdbm.so.6` and `/usr/lib64/libgdbm.so.5` are different versions of GDBM. Linking one for the other will satisfy the baseline "does the file exist" requirement, but at runtime, when symbols are loaded dynamically, you may (almost certainly will) discover missing symbols, or symbols that behave differently.

Except if these have upwards compatability?

**Comment by freakboy3742** [comment] 2022-04-12 23:45
I'll take your word for that. I don't know GDBM well enough to be able to comment. If it works for you, then go right ahead; personally, I wouldn't be relying on it.

**Comment by mavavilj** [comment] 2022-04-13 00:14
Okay so essentially the limitations are just in order fix a "tested" configuration?

**Comment by freakboy3742** [comment] 2022-04-13 00:37
In that case you have a choice:

1. Find a way to obtain or compile those binaries for Ubuntu 18.04
2. Develop using a more recent version of Linux, and accept that there will be more recent minimum requirements on your resulting AppImage

Briefcase provides "easy, out of the box" support for the former. It provides "available, but requires work on the part of the user" support for the latter.

It simply isn't plausible for us to support every Linux version. We've picked Ubuntu 18.04 because it's recent enough to have support for most things, but not so ancient that it's incompatible with everything. If that base line isn't suitable for your use case, then that's fine - but you then need to compile your own Python support build, for your own preferred version of Linux. What you can't do is provided Ubuntu 18.04 support build, which works fine when used in the environment for which it has been compiled, stick it into a more recent linux and then complain that it doesn't work. It only works in the environment for which it is intended.

**Comment by freakboy3742** [comment] 2022-04-22 02:24
I'm going to close this issue, as the underlying problem is with Briefcase. We have a cluster of Linux AppImage packaging bugs that we need to address (see beeware/briefcase#718 for details), of which this is just one manifestation.

**Closed by freakboy3742** 2022-04-22 02:24 UTC
Labels: bug, help wanted
