### ISSUE TITLE
Need help with installing dependencies

### ISSUE THREAD

**Issue by karimkhanp** [beeware/beeware#157] opened 2022-06-02 15:12 UTC
When I was trying to create iOS briefcase, my Internet got interrupted during Python-3.7-iOS-support.b9.tar.gz dependency installation.

```
briefcase create iOS

Application testing already exists; overwrite [y/N]? y

[testing] Removing old application bundle...

[testing] Generating application template...
Using app template: https://github.com/beeware/briefcase-iOS-Xcode-template.git, branch 3.7
Using existing template (sha 4372bd14d581a2d95fda83b7b477380b403045a5, updated Tue May 17 09:51:44 2022)

[testing] Installing support package...
Using support package https://briefcase-support.org/python?platform=iOS&version=3.7
... using most recent revision
Python-3.7-iOS-support.b9.tar.gz already downloaded
Unpacking support package...

Unable to unpack support package 'https://briefcase-support.org/python?platform=iOS&version=3.7'
```

Now it thinks package download was completed and extracting the same half downloaded tar file. 

I tried to search for "Python-3.7-iOS-support.b9.tar.gz" on my machine but I don't see this file any where. 
I restarted my machine just to remove if file is in cache but still giving same error.

Is there any way I redownload the same package and overwrite current.

**Comment by freakboy3742** [comment] 2022-06-03 03:08
The support file cache is located in `~/.briefcase/support`; if you delete the existing file in that directory, and re-run briefcase, it should re-download (hopefully successfully, this time!).

There isn't currently a user-facing command to do this, but there probably should be. I've just opened beeware/briefcase#753 to track this as a feature request; I'll close this ticket since the problem isn't with the tutorial, but with the tool the tutorial is using.

**Closed by freakboy3742** 2022-06-03 03:08 UTC
