### ISSUE TITLE
briefcase run fails on MacOC Big Sur due to "User doesn't have permission to launch the app" error

### ISSUE THREAD

**Issue by hiroono** [beeware/beeware#134] opened 2021-12-23 13:35 UTC
I am on Tutorial 3 and run the app when I encountered this error:

```
(beeware-venv) ono@MasahironoAir helloworld % briefcase run

[helloworld] Starting app...

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2436, NSUnderlyingError=0x13962a1a0 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x13962a920 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 153}}}}}

Unable to start app helloworld.
```

I found this on the internet: https://developer.apple.com/forums/thread/666611

So I tried:
```
(beeware-venv) ono@MasahironoAir Hello World % codesign --force --deep -sign - Hello\ World.app
error: The specified item could not be found in the keychain.
```

It seems this issue is not reported here. Perhaps a new Big Sur issue? Please help!

**Comment by n8henrie** [comment] 2022-02-06 21:10
You're missing a hyphen: `-sign` should be `--sign`.

On  my M1 Mac running 12.2 and Python 3.10, I was also getting:

```
$ briefcase run

[helloworld] Starting app...

The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000012b1950 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

Unable to start app helloworld.
```

I was unable to manually open the application bundle by double-clicking or by right-clicking and going to `Open`.

After the below, it successfully ran.

```console
$ codesign --force --deep --sign - macOS/app/Hello\ World/Hello\ World.app/
$ briefcase run

[helloworld] Starting app...

```

**Comment by freakboy3742** [comment] 2022-03-28 04:27
This appears to be caused by beeware/briefcase#664. That ticket also contains a [workaround](https://github.com/beeware/briefcase/issues/664#issuecomment-1055037121) that will work in the short term. 

Closing as there is a known workaround, and the underlying problem is with Briefcase, not the tutorial itself.

**Closed by freakboy3742** 2022-03-28 04:27 UTC
